import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { NavBarComponent } from "../../component/nav-bar/nav-bar.component";
import { FooterComponent } from "../../component/footer/footer.component";

@Component({
  selector: 'app-gallery',
  standalone: true,
  imports: [CommonModule, NavBarComponent, FooterComponent],
  templateUrl: './gallery.component.html',
  styleUrl: './gallery.component.css'
})
export class GalleryComponent {

  Allimages = [
    { url: 'assets/images/deulex21.jpeg', title: '' },
    { url: 'assets/images/deulex22.jpeg', title: '' },
    { url: 'assets/images/deulex23.jpeg', title: '' },
    { url: 'assets/images/deulex24.jpeg', title: '' },
    { url: 'assets/images/deulex25.jpeg', title: '' },
    { url: 'assets/images/deulex1.jpeg', title: '' },
    { url: 'assets/images/deulex5.jpeg', title: '' },
    { url: 'assets/images/deulex6.jpeg', title: '' },
    { url: 'assets/images/deulex9.jpeg', title: ' ' },
    { url: 'assets/images/deulex30.jpeg', title: ' ' },
    { url: 'assets/images/deulex11.jpeg', title: ' ' },
    { url: 'assets/images/deulex12.jpeg', title: ' ' },
    { url: 'assets/images/deulex13.jpeg', title: ' ' },
    { url: 'assets/images/deulex14.jpeg', title: ' ' },
    { url: 'assets/images/deulex15.jpeg', title: ' ' },
    { url: 'assets/images/deulex16.jpeg', title: ' ' },
    { url: 'assets/images/deulex31.jpeg', title: ' ' },
    { url: 'assets/images/deulex18.jpeg', title: ' ' },
    { url: 'assets/images/deulex19.jpeg', title: ' ' },
    { url: 'assets/images/deulex20.jpeg', title: ' ' },


    { url: 'assets/images/froom20.jpeg', title: '' },
    { url: 'assets/images/froom21.jpeg', title: '' },
    { url: 'assets/images/froom22.jpeg', title: '' },
    { url: 'assets/images/froom23.jpeg', title: '' },
    { url: 'assets/images/froom24.jpeg', title: '' },
    { url: 'assets/images/froom25.jpeg', title: '' },
    { url: 'assets/images/froom26.jpeg', title: '' },
    { url: 'assets/images/froom27.jpeg', title: '' },
    { url: 'assets/images/froom28.jpeg', title: ' ' },
    { url: 'assets/images/froom29.jpeg', title: ' ' },
    { url: 'assets/images/froom30.jpeg', title: ' ' },
    { url: 'assets/images/froom41.jpeg', title: ' ' },
    { url: 'assets/images/froom42.jpeg', title: ' ' },
    { url: 'assets/images/froom43.jpeg', title: ' ' },
    { url: 'assets/images/froom44.jpeg', title: ' ' },
    { url: 'assets/images/froom45.jpeg', title: ' ' },
    { url: 'assets/images/froom46.jpeg', title: ' ' },
    { url: 'assets/images/froom47.jpeg', title: ' ' },
    { url: 'assets/images/froom49.jpeg', title: ' ' },
    { url: 'assets/images/froom50.jpeg', title: ' ' },


    { url: 'assets/images/rdesign13.jpeg', title: '' },
    { url: 'assets/images/rdesign14.jpeg', title: '' },
    { url: 'assets/images/rdesign15.jpeg', title: '' },
    { url: 'assets/images/rdesign16.jpeg', title: '' },
    { url: 'assets/images/rdesign17.jpeg', title: '' },
    { url: 'assets/images/rdesign18.jpeg', title: '' },
    { url: 'assets/images/rdesign19.jpeg', title: '' },
    { url: 'assets/images/rdesign20.jpeg', title: '' },
    { url: 'assets/images/rdesign21.jpeg', title: ' ' },
    { url: 'assets/images/rdesign22.jpeg', title: ' ' },
    { url: 'assets/images/rdesign23.jpeg', title: ' ' },
    { url: 'assets/images/rdesign24.jpeg', title: ' ' },
    { url: 'assets/images/rdesign25.jpeg', title: ' ' },
    { url: 'assets/images/rdesign26.jpeg', title: ' ' },
    { url: 'assets/images/rdesign27.jpeg', title: ' ' },
    { url: 'assets/images/rdesign28.jpeg', title: ' ' },
    { url: 'assets/images/promote3.jpeg', title: ' ' },
    { url: 'assets/images/rdesign30.jpeg', title: ' ' },
    { url: 'assets/images/rdesign31.jpeg', title: ' ' },
    { url: 'assets/images/rdesign12.jpeg', title: ' ' },

    { url: 'assets/images/viewup2.jpeg', title: '' },
    { url: 'assets/images/viewup3.jpeg', title: '' },
    { url: 'assets/images/view1.jpeg', title: '' },
    { url: 'assets/images/view2.jpeg', title: '' },
    { url: 'assets/images/view3.jpeg', title: '' },
    { url: 'assets/images/view4.jpeg', title: '' },
    { url: 'assets/images/view5.jpeg', title: '' },
    { url: 'assets/images/view6.jpeg', title: '' },
    { url: 'assets/images/promote4.jpeg', title:''},
    { url: 'assets/images/view8.jpeg', title: ' ' },
    { url: 'assets/images/view9.jpeg', title: ' ' },
    { url: 'assets/images/promote6.jpeg', title: ' ' },
    { url: 'assets/images/view11.jpeg', title: ' ' },
    { url: 'assets/images/promote1.jpeg', title: ' ' },
    { url: 'assets/images/view13.jpeg', title: ' ' },
    { url: 'assets/images/view14.jpeg', title: ' ' },
    { url: 'assets/images/view15.jpeg', title: ' ' },
    { url: 'assets/images/view20.jpeg', title: ' ' },
    { url: 'assets/images/view21.jpeg', title: ' ' },
    { url: 'assets/images/view22.jpeg', title: ' ' },

    { url: 'assets/images/en5.jpeg', title: '' },
    { url: 'assets/images/en6.jpeg', title: '' },
    { url: 'assets/images/en9.jpeg', title: '' },
    { url: 'assets/images/en11.jpeg', title: '' },
    { url: 'assets/images/en13.jpeg', title: '' },
    { url: 'assets/images/en15.jpeg', title: '' },
    { url: 'assets/images/en4.jpeg', title: '' },
    { url: 'assets/images/en24.jpeg', title: '' },
    { url: 'assets/images/en5.jpeg', title:''},
    { url: 'assets/images/garden11.jpeg', title: ' ' },
    { url: 'assets/images/garden21.jpeg', title: ' ' },
    { url: 'assets/images/garden13.jpeg', title: ' ' },
    { url: 'assets/images/garden20.jpeg', title: ' ' },
    { url: 'assets/images/garden7.jpeg', title: ' ' },
    { url: 'assets/images/washroom24.jpeg', title: ' ' },
    { url: 'assets/images/washroom22.jpeg', title: ' ' },
    { url: 'assets/images/washroom17.jpeg', title: ' ' },
    { url: 'assets/images/washroom9.jpeg', title: ' ' },
    { url: 'assets/images/washroom6.jpeg', title: ' ' },
    { url: 'assets/images/washroom15.jpeg', title: ' ' },




    { url: 'assets/images/b1.jpeg', title: 'Elephant Safari' },
    { url: 'assets/images/b2.jpeg', title: 'Leopard Watch' },
    { url: 'assets/images/b3.jpeg', title: 'Jeep Adventure' },
    { url: 'assets/images/b4.jpeg', title: 'Bird Watching' },
    { url: 'assets/images/b5.jpeg', title: 'Elephant Safari' },
    { url: 'assets/images/b6.jpeg', title: 'Leopard Watch' },
    { url: 'assets/images/b7.jpeg', title: 'Jeep Adventure' },
    { url: 'assets/images/b8.jpeg', title: 'Bird Watching' },
    { url: 'assets/images/b9.jpeg', title: 'Elephant Safari' },
    { url: 'assets/images/b10.jpeg', title: 'Leopard Watch' },
    { url: 'assets/images/b11.jpeg', title: 'Jeep Adventure' },
    { url: 'assets/images/b12.jpeg', title: 'Bird Watching' },
    { url: 'assets/images/b13.jpeg', title: 'Jeep Adventure' },
    { url: 'assets/images/b14.jpeg', title: 'Bird Watching' },
    { url: 'assets/images/b15.jpeg', title: 'Elephant Safari' },
    { url: 'assets/images/b16.jpeg', title: 'Leopard Watch' },
    { url: 'assets/images/b17.jpeg', title: 'Jeep Adventure' },
    { url: 'assets/images/b18.jpeg', title: 'Bird Watching' },
    { url: 'assets/images/b19.jpeg', title: 'Jeep Adventure' },
    { url: 'assets/images/b20.jpeg', title: 'Bird Watching' }


  ];

}
